### ISSUE TITLE
Access token fails

### ISSUE THREAD

**Issue by arikadiusz** [jimmyjudas/LightwaveRFLinkPlusSharp#5]
> LightwaveRFLinkPlusSharp.InvalidRefreshTokenException: 'All attempts to get a new access token have failed. For details on how to pass in a seed refresh token, see the summary on the LightwaveAPI constructor. For debugging purposes, a record of the events leading to this failure can be found in this exception's TokenRequestLog property'

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LightwaveRFLinkPlusSharp;

namespace Lightwave
{
    class Program
    {
        static void Main(string[] args)
        {
            LightwaveLogic logic = new LightwaveLogic();

            logic.DoSomething();

            Console.Read();
        }
    }

    class LightwaveLogic
    {
        public async void DoSomething()
        {
            LightwaveAPI api = new LightwaveAPI("<MY BASIC>", "<MY REFRESH>");

            Device[] devices = await api.GetDevicesInFirstStructureAsync();

            Console.WriteLine($"{devices.Count()} devices discovered:");
            foreach (var discoveredDevice in devices)
            {
                Console.WriteLine($"\t{discoveredDevice.Name}");

                await api.PopulateFeatureValuesAsync(discoveredDevice);

                foreach (var deviceFeature in discoveredDevice.Features)
                {
                    Console.WriteLine($"\t\t{deviceFeature}");
                }
            }
        }
    }
}

**Comment by jimmyjudas** [comment]
Hi arikadiusz. Did this happen the first time you ever ran the program, the first time you ran it for a while or after it had been running for a while? Also, can you provide the contents of the exception's TokenRequestLog property?

**Comment by arikadiusz** [comment]
> Hi arikadiusz. Did this happen the first time you ever ran the program, the first time you ran it for a while or after it had been running for a while? Also, can you provide the contents of the exception's TokenRequestLog property?

Hi Jimmy,

it happen when I run the program for the first time ever.
here's what I can see inside of TokenRequestLog property when the exception happens :
```"Access token requested for request d58baeb8-d134-4fb6-8284-aa54806f7f50\r\nRefreshing access token\r\n\tUsing Seed refresh token\r\n"``

**Comment by jimmyjudas** [comment]
That's strange. Are you sure you're using the full access ("basic") token and you haven't missed a letter or added a space at one end? Can you try requesting a new refresh token on the website and then using that in the LightwaveAPI constructor?

**Comment by jimmyjudas** [comment]
Closing this issue due to a lack of response. Hope you got things working, arikadiusz!
